create table bill_details (id bigint generated by default as identity, bill_date timestamp, gross_amount double not null, user_id bigint, primary key (id));
create table item (id bigint generated by default as identity, item_category_code varchar(255), item_name varchar(255), item_price double not null, item_type varchar(255), primary key (id));
create table item_order (id bigint generated by default as identity, item_quantity integer not null, bill_id bigint, item_order_id bigint, primary key (id));
create table item_ref_data (id integer generated by default as identity, item_ref_data_code varchar(255), item_refe_data_text varchar(255), primary key (id));
create table user (id bigint generated by default as identity, created_date timestamp, email varchar(255), mobile_number varchar(255), name varchar(255), user_type varchar(255), primary key (id));
create table user_ref_data (id integer generated by default as identity, user_ref_data_code varchar(255), user_ref_data_text varchar(255), primary key (id));
alter table bill_details add constraint FK9mb6kvqadpne2dhpadv2aulem foreign key (user_id) references user;
alter table item_order add constraint FKsp3d0d1793iu0ux6qdhbhk5co foreign key (bill_id) references bill_details;
alter table item_order add constraint FKjy4o6m23d3ppsxl0kemyrv6hg foreign key (item_order_id) references item;

